version: '3.8'

services:
  myapp:
    image: slackbot-submissions:v0.1
    ports:
      - "443:443"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Add other environment variables as needed
    networks:
      - default

networks:
  default:
    driver: bridge
